export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_PAGINATION = "FETCH_COURSES_PAGINATION";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FET__COURSE_CATEGORY = "FET__COURSE_CATEGORY";